spring:
  application:
    name: eureka-application-provider
server:
  port: 8001

#  profiles:
#    active: peer3
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka,http://localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka